export interface Options {
  value: string;
  label: string;
}

export const specialtyFalse: Options[] = [
  { value: '', label: 'Select an option' },
  { value: 'Comunicación', label: 'Communication' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Health Coach', label: 'Health Coach' },
  { value: 'Ingeniero en alimentos', label: 'Food Engineer' },
  { value: 'Químico en alimentos', label: 'Food chemist' },
  { value: 'Otro', label: 'Another' },
];

export const specialtyTrue: Options[] = [
  { value: '', label: 'Select an option' },
  { value: 'Nutrición', label: 'Nutrition' },
  { value: 'Gastroenterología', label: 'Gastroenterology' },
  { value: 'Pediatría', label: 'Pediatrics' },
  { value: 'Medicina general', label: 'General Medicine' },
  { value: 'Medicina familiar', label: 'Family Medicine' },
  { value: 'Enfermería', label: 'Nursing' },
  { value: 'Estudiante nutrición', label: 'Nutrition student' },
  { value: 'Estudiante medicina', label: 'Medical student' },
  { value: 'Otro', label: 'Another' },
];

export const workAreaOptions: Options[] = [
  { value: '', label: 'Select an option' },
  { value: 'Investigación', label: 'Research' },
  { value: 'Docente', label: 'Faculty' },
  { value: 'Consulta pública/privada', label: 'Public/private consultation' },
  { value: 'Industria de alimentos', label: 'Food industry' },
  { value: 'Otro', label: 'Another' },
];

export const nationalityData: Options[] = [
  { value: '', label: 'Select an option' },
  { value: 'AF', label: 'Afghanistan' },
  { value: 'AL', label: 'Albania' },
  { value: 'DE', label: 'Germany' },
  { value: 'DZ', label: 'Algeria' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AU', label: 'Australia' },
  { value: 'BE', label: 'Belgium' },
  { value: 'BR', label: 'Brazil' },
  { value: 'CA', label: 'Canada' },
  { value: 'CL', label: 'Chile' },
  { value: 'CN', label: 'China' },
  { value: 'CO', label: 'Colombia' },
  { value: 'KR', label: 'South Korea' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'CU', label: 'Cuba' },
  { value: 'DK', label: 'Denmark' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'EG', label: 'Egypt' },
  { value: 'ES', label: 'Spain' },
  { value: 'FI', label: 'Finland' },
  { value: 'FR', label: 'France' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'GR', label: 'Greece' },
  { value: 'IN', label: 'India' },
  { value: 'IT', label: 'Italy' },
  { value: 'JP', label: 'Japan' },
  { value: 'MX', label: 'Mexico' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'PE', label: 'Peru' },
  { value: 'PT', label: 'Portugal' },
  { value: 'RU', label: 'Russia' },
  { value: 'SE', label: 'Sweden' },
  { value: 'TH', label: 'Thailand' },
  { value: 'TN', label: 'Tunisia' },
  { value: 'TR', label: 'Turkey' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'US', label: 'United States' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Vietnam' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'AT', label: 'Austria' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'BH', label: 'Bahrain' },
  { value: 'BO', label: 'Bolivia' },
  { value: 'CA', label: 'Canada' },
  { value: 'CY', label: 'Cyprus' },
  { value: 'CZ', label: 'Czech Republic' },
  { value: 'DO', label: 'Dominican Republic' },
  { value: 'EE', label: 'Estonia' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HU', label: 'Hungary' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IE', label: 'Ireland' },
  { value: 'IL', label: 'Israel' },
  ];