export interface Options {
  value: string;
  label: string;
}

export const specialtyFalse: Options[] = [
  { value: '', label: 'Selecciona una opción' },
  { value: 'Comunicación', label: 'Comunicación' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Health Coach', label: 'Health Coach' },
  { value: 'Ingeniero en alimentos', label: 'Ingeniero en alimentos' },
  { value: 'Químico en alimentos', label: 'Químico en alimentos' },
  { value: 'Otro', label: 'Otro' },
];

export const specialtyTrue: Options[] = [
  { value: '', label: 'Selecciona una opción' },
  { value: 'Nutrición', label: 'Nutrición' },
  { value: 'Gastroenterología', label: 'Gastroenterología' },
  { value: 'Pediatría', label: 'Pediatría' },
  { value: 'Medicina general', label: 'Medicina general' },
  { value: 'Medicina familiar', label: 'Medicina familiar' },
  { value: 'Enfermería', label: 'Enfermería' },
  { value: 'Estudiante nutrición', label: 'Estudiante nutrición' },
  { value: 'Estudiante medicina', label: 'Estudiante medicina' },
  { value: 'Otro', label: 'Otro' },
];

export const workAreaOptions: Options[] = [
  { value: '', label: 'Selecciona una opción' },
  { value: 'Investigación', label: 'Investigación' },
  { value: 'Docente', label: 'Docente' },
  { value: 'Consulta pública/privada', label: 'Consulta pública/privada' },
  { value: 'Industria de alimentos', label: 'Industria de alimentos' },
  { value: 'Otro', label: 'Otro' },
];

export const nationalityData: Options[] = [
  { value: '', label: 'Selecciona una opción' },
  { value: 'AF', label: 'Afganistán' },
  { value: 'AL', label: 'Albania' },
  { value: 'DE', label: 'Alemania' },
  { value: 'DZ', label: 'Argelia' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AU', label: 'Australia' },
  { value: 'BE', label: 'Bélgica' },
  { value: 'BR', label: 'Brasil' },
  { value: 'CA', label: 'Canadá' },
  { value: 'CL', label: 'Chile' },
  { value: 'CN', label: 'China' },
  { value: 'CO', label: 'Colombia' },
  { value: 'KR', label: 'Corea del Sur' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'CU', label: 'Cuba' },
  { value: 'DK', label: 'Dinamarca' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'EG', label: 'Egipto' },
  { value: 'ES', label: 'España' },
  { value: 'FI', label: 'Finlandia' },
  { value: 'FR', label: 'Francia' },
  { value: 'GB', label: 'Reino Unido' },
  { value: 'GR', label: 'Grecia' },
  { value: 'IN', label: 'India' },
  { value: 'IT', label: 'Italia' },
  { value: 'JP', label: 'Japón' },
  { value: 'MX', label: 'México' },
  { value: 'NL', label: 'Países Bajos' },
  { value: 'PE', label: 'Perú' },
  { value: 'PT', label: 'Portugal' },
  { value: 'RU', label: 'Rusia' },
  { value: 'SE', label: 'Suecia' },
  { value: 'TH', label: 'Tailandia' },
  { value: 'TN', label: 'Túnez' },
  { value: 'TR', label: 'Turquía' },
  { value: 'UA', label: 'Ucrania' },
  { value: 'US', label: 'Estados Unidos' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Vietnam' },
  { value: 'ZA', label: 'Sudáfrica' },
  { value: 'AT', label: 'Austria' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'BH', label: 'Baréin' },
  { value: 'BO', label: 'Bolivia' },
  { value: 'CA', label: 'Canadá' },
  { value: 'CY', label: 'Chipre' },
  { value: 'CZ', label: 'República Checa' },
  { value: 'DO', label: 'República Dominicana' },
  { value: 'EE', label: 'Estonia' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HU', label: 'Hungría' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IE', label: 'Irlanda' },
  { value: 'IL', label: 'Israel' },
];
